### PR TITLE
done backend architecture

### PR DESCRIPTION
**Pull request by ProjectsByJackHe**
here, I have finished building the backend architecture. Some notes about firebase:

Each document represents a continent. Or "group".

In each group, there is a list of links array.

### CODE REVIEW

**Comment by mcao** [comment]
uhHHH you leaked our firebase credentials

**Comment by mcao** [comment]
Might also want to add .env to .gitignore

**Comment by mcao** [comment]
Should we merge this now and make the changes for sorting later? We also have to migrate the data over to the database.

**Comment by ProjectsByJackHe** [comment]
> Should we merge this now and make the changes for sorting later? We also have to migrate the data over to the database.

We should merge this now as this is a top priority and the sorting is just an extra bonus on the admin dashboard. We can just update the database manually for now. But before we merge, we need to migrate all data from the dummy constants to the database.

**Pull request closed without merging**
